routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('admin', 'AdminController@index');

Route::get('/products', 'ProductsController@index');

Route::resource('product','ProductsController');
Route::resource('categories','CategoriesController');

app/Admin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Admin extends Eloquent
{
    
}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['title','category','description','price'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;

use App\Admin;
use App\Category;
use App\Product;
use Illuminate\Http\Request;

class AdminController extends Controller
{

    public function index() {
        $categories = Category::all();
        $categories->toarray();

        $products = Product::all();
        $products->toarray();
        
        return view('layouts.adminPanel', array('categories' =>  $categories, 'products' => $products));
	}
    

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;


class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $categories = Category::all();
        $categories->toarray();
        return view('categories.show', array('categories' =>  $categories));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Input::all();
        
        Category::create($input);

        return Redirect::route('categories.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $category = Category::find($id);
       return view('categories.show', array('category' => $category));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);
        if (is_null($category)) {
            return Redirect::route('admin');
        }

        return view('categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $input = Input::all();
         $category = Category::find($id);
         $category->update($input);
        return Redirect::route('categories.index');
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Category::find($id)->delete();
        return Redirect::route('categories.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Validator;


class ProductsController extends Controller
{
      /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $products = Product::all();
        $products->toarray();
        return view('product.show', array('products' =>  $products));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = Input::all();
        
        Product::create($input);

        return Redirect::route('product.index');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       $products = Product::find($id);
       return view('product.show', array('products' => $products));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);
        if (is_null($product)) {
            return Redirect::route('admin');
        }

        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $input = Input::all();
         $products = Product::find($id);
         $products->update($input);
        return Redirect::route('product.index');
       
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::find($id)->delete();
        return Redirect::route('product.index');
    }
}

resources/views/categories/create.blade.php
@section('main')

<h1>Create Category</h1>

{{ Form::open(array('route' => 'categories.store')) }}
    <ul>

        
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name') }}
        
            {{ Form::submit('Save', array('class' => 'btn')) }}
        
    </ul>
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">Error!</li>')) }}
    </ul>
@endif

resources/views/categories/edit.blade.php
@section('main')

<h1>Edit Category</h1>
{{ Form::model($category, array('method' => 'PATCH', 'route' => array('categories.update', $category->id))) }}
    <ul>
        <li>
            {{ Form::label('name', 'Name:') }}
            {{ Form::text('name') }}
        
        <li>
            {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
            <a href="{{ url('/admin') }}">Cancel</a>

        </li>
    </ul>
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

resources/views/categories/show.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>Categories:</title>
    <a href="{{ url('admin') }}">Back to panel</a>
  </head>
  <body>
  @foreach ($categories as $cat)
    <h1>Category:</h1>
    <ul>
      <li>Name: {{ $cat->name }}</li>
    </ul>
@endforeach
  </body>
</html>

resources/views/layouts/adminPanel.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Admin Panel</title>
        {!! Html::style('assets/css/bootstrap.css') !!}
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }


            td {
                font-size: 15px;
                color: black;
                font-weight: 600;

            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }

        </style>
    </head>
    <body>
        <div class="flex-center position-ref full-height">

            <div class="content">
                @section('main')


                <h1>All Categories</h1>
                <a href="{{ url('product/create') }}">Add new product</a>
                <a href="{{ url('categories/create') }}">Add new category</a>

                @if ($categories->count())
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($categories as $cat)
                                <tr>
                                    <td>{{ $cat->name }}</td>
                                    <td><a class="btn btn-info" href="{{ route('categories.edit', ['id' => $cat->id]) }}">Edit</a></td>
                                    <!--<td><a class="btn btn-danger" href="{{  route('categories.destroy', ['id' => $cat->id]) }}">Delete</a></td>-->
                                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('categories.destroy', $cat->id))) }}                       
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                            {{ Form::close() }}
                                    </td>
                                </tr>-
                            @endforeach
                            
                        </tbody>
                    
                    </table>
                @else
                    There are no categories
                @endif


                <h1>All Products</h1>

                @if ($products->count())
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach ($products as $prod)
                                <tr>
                                    <td>{{ $prod->title }}</td>
                                    <td>{{ $prod->category }}</td>
                                    <td>{{ $prod->description }}</td>
                                    <td>{{ $prod->price }}</td>
                                    <td><a class="btn btn-info" href="{{ route('product.edit', ['id' => $prod->id]) }}">Edit</a></td>
                                    <td>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('product.destroy', $prod->id))) }}                       
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                            {{ Form::close() }}
                                    </td>
                                </tr>-
                            @endforeach
                            
                        </tbody>
                    
                    </table>
                @else
                    There are no products
                @endif

resources/views/product/create.blade.php
@section('main')

<h1>Create Product</h1>

{{ Form::open(array('route' => 'product.store')) }}
    <ul>

        
          <li>
            {{ Form::label('title', 'Title:') }}
            {{ Form::text('title') }}
        </li>
        <li>
            {{ Form::label('category', 'Category:') }}
            {{ Form::text('category') }}
        </li>
        <li>
            {{ Form::label('description', 'Description:') }}
            {{ Form::text('description') }}
        </li>
        <li>
            {{ Form::label('price', 'Price:') }}
            {{ Form::text('price') }}
        </li>
        
        
            {{ Form::submit('Save', array('class' => 'btn')) }}
        
    </ul>
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">Error!</li>')) }}
    </ul>
@endif

resources/views/product/edit.blade.php
@section('main')

<h1>Edit Product</h1>
{{ Form::model($product, array('method' => 'PATCH', 'route' => array('product.update', $product->id))) }}
    <ul>
        <li>
            {{ Form::label('title', 'Title:') }}
            {{ Form::text('title') }}
        </li>
        <li>
            {{ Form::label('category', 'Category:') }}
            {{ Form::text('category') }}
        </li>
        <li>
            {{ Form::label('description', 'Description:') }}
            {{ Form::text('description') }}
        </li>
        <li>
            {{ Form::label('price', 'Price:') }}
            {{ Form::text('price') }}
        </li>
        <li>
            {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
            <a href="{{ url('/admin') }}">Cancel</a>

        </li>
    </ul>
{{ Form::close() }}

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

resources/views/product/show.blade.php
<!DOCTYPE html>
<html>
  <head>
    <title>Products:</title>
    <a href="{{ url('admin') }}">Back to panel</a>
  </head>
  <body>
  @foreach ($products as $prod)
    <h1>Products:</h1>
    <ul>
      <li>Title: {{ $prod->title }}</li>
      <li>Category: {{ $prod->category }}</li>
      <li>Description: {{ $prod->description }}</li>
      <li>Price: {{ $prod->price }}</li>
    </ul>
@endforeach
  </body>
</html>